version: "3.5"

services:
  volumes-provisioner:
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: "1000:1000:0755:/tmp/certs"
    volumes:
    - "./certs:/tmp/certs"
    network_mode: none
  cert-gen:
    image: eventstore/es-gencert-cli:1.0.2
    entrypoint: bash
    command: >
      -c "es-gencert-cli create-ca -out /tmp/certs/ca &&
          es-gencert-cli create-node -ca-certificate /tmp/certs/ca/ca.crt -ca-key /tmp/certs/ca/ca.key -out \
          /tmp/certs/node1 -ip-addresses 127.0.0.1,172.30.240.11 -dns-names localhost &&
          es-gencert-cli create-node -ca-certificate /tmp/certs/ca/ca.crt -ca-key /tmp/certs/ca/ca.key -out \
          /tmp/certs/node2 -ip-addresses 127.0.0.1,172.30.240.12 -dns-names localhost &&
          es-gencert-cli create-node -ca-certificate /tmp/certs/ca/ca.crt -ca-key /tmp/certs/ca/ca.key -out \
          /tmp/certs/node3 -ip-addresses 127.0.0.1,172.30.240.13 -dns-names localhost"
    user: "1000:1000"
    volumes:
      - "./certs:/tmp/certs"
    depends_on:
      - volumes-provisioner
  esdb-node1:
    build: ./
    env_file:
      - shared.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.30.240.12:2113,172.30.240.13:2113
      - EVENTSTORE_INT_IP=172.30.240.11
      - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node1/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node1/node.key
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2111
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1111
    ports:
      - 1111:1113
      - 2111:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.11
    volumes:
      - ./certs:/etc/eventstore/certs
    restart: unless-stopped
    depends_on:
      - cert-gen

  esdb-node2:
    build: ./
    env_file:
      - shared.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.30.240.11:2113,172.30.240.13:2113
      - EVENTSTORE_INT_IP=172.30.240.12
      - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node2/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node2/node.key
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2112
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1112
    ports:
      - 1112:1113
      - 2112:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.12
    volumes:
      - ./certs:/etc/eventstore/certs
    restart: unless-stopped
    depends_on:
      - cert-gen

  esdb-node3:
    build: ./
    env_file:
      - shared.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.30.240.11:2113,172.30.240.12:2113
      - EVENTSTORE_INT_IP=172.30.240.13
      - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node3/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node3/node.key
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.13
    volumes:
      - ./certs:/etc/eventstore/certs
    restart: unless-stopped
    depends_on:
      - cert-gen

networks:
  clusternetwork:
    name: eventstoredb.local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.240.0/24
