name: Common

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - master
      - release/*
    tags:
      - oss-v*
      - v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

env:
  NuGetPackageSourceCredentials_EventStore: Username=${{ vars.ORG_GH_BOT_USERNAME }};Password=${{ secrets.ORG_GH_BOT_AUTOMATION }}
  NuGetPackageSourceCredentials_KurrentDB: Username=${{ vars.ORG_GH_BOT_USERNAME }};Password=${{ secrets.ORG_GH_BOT_AUTOMATION }}

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    name: ci/github/scan-vulnerabilities
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install net8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Scan for Vulnerabilities
      run: |
        cd src
        dotnet restore
        dotnet list package --vulnerable --include-transitive | tee vulnerabilities.txt
        ! cat vulnerabilities.txt | grep -q "has the following vulnerable packages"
  protolock:
    runs-on: ubuntu-latest
    name: ci/github/protolock
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Protolock Status
      shell: bash
      run: |
        ./protolock.sh status --uptodate
  docker-compose:
    runs-on: ubuntu-latest
    name: ci/github/docker-compose
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Github Registry Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com/eventstore
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Compose Smoke Test
      run: |
        docker compose -e NuGetPackageSourceCredentials_EventStore=${{ env.NuGetPackageSourceCredentials_EventStore }} -e NuGetPackageSourceCredentials_KurrentDB=${{ env.NuGetPackageSourceCredentials_KurrentDB }} build
        docker compose up --detach
        printf 'Waiting for cluster'
        timeout 60 bash -c -- 'until $(curl --output /dev/null --silent --insecure --fail https://localhost:2113/health/live); do printf '.'; sleep 2; done'
        docker compose down
