name: Initiate Client Release
 
on:
  push:
    tags:
      - "dotnet-client-v*"
 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "version=${GITHUB_REF:25}" >> $GITHUB_OUTPUT
      - name: Perform Release 
        run: |
          curl -X POST https://api.github.com/repos/EventStore/TrainStation/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_PAT }} \
          --data '{"event_type": "client-release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "version": "${{ steps.get_version.outputs.version }}" }}'