name: Server development project automations for issues

on:
  issues:
    types:
      - milestoned
jobs:
  call-workflow:
    uses: EventStore/Automations/.github/workflows/development-project-automation.yml@master
    with:
      resource-node-id: ${{ github.event.issue.node_id }}
      event-action: ${{ github.event.action }}
      event-name: ${{ github.event_name }}
    secrets:
      project-number: ${{ secrets.SERVER_DEV_PROJECT_NUMBER }}
      token: ${{ secrets.ORG_ACCESS_TOKEN }}